# Generated by Django 5.0.4 on 2024-06-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nom',
            name='char',
            field=models.CharField(blank=True, max_length=10000000000),
        ),
    ]
